name: SKHathaway
favicon: null
layout_spectrum: 0.8049932189751416
typography_spectrum: 0.8528344077058136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0100'
    - '#b8b892'
    - '#9b3b01'
    - '#f6feff'
    - '#8b8666'
  brandStrength: 0.9683913900516927
  lightness: 0.5147686798591167
  saturation: 0.3926775334402919
  rhythmicContrast: 0.39655004628002644
purpose: []
